# Generated by Django 4.2.4 on 2024-09-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cyber", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="autus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("password", models.EmailField(max_length=254)),
                (
                    "captcha",
                    models.ImageField(blank=True, null=True, upload_to="captcha"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="UserCheck",
        ),
    ]
