# Generated by Django 4.2.4 on 2024-09-03 04:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cyber", "0002_autus_delete_usercheck"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="autus",
            new_name="UserCheck",
        ),
    ]
